{{- $port := .Values.devsecdb.option.port -}}
apiVersion: v1
kind: Service
metadata:
  name: devsecdb-entrypoint
  namespace: {{ template "devsecdb.namespace" . }}
  labels:
    {{- include "devsecdb.labels" . | nindent 4}}
spec:
  type: ClusterIP
  selector:
    app: devsecdb
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ $port }}
